In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

## Loading The Dataset

In [2]:
jobs_data = pd.read_csv("dice_com-job_us_sample.csv")

## Exploring First Part of the Dataset

In [3]:
jobs_data.head()

advertiserurl  \
0  https://www.dice.com/jobs/detail/AUTOMATION-TE...   
1  https://www.dice.com/jobs/detail/Information-S...   
2  https://www.dice.com/jobs/detail/Business-Solu...   
3  https://www.dice.com/jobs/detail/Java-Develope...   
4  https://www.dice.com/jobs/detail/DevOps-Engine...   

                             company  \
0  Digital Intelligence Systems, LLC   
1  University of Chicago/IT Services   
2               Galaxy Systems, Inc.   
3                      TransTech LLC   
4                   Matrix Resources   

                            employmenttype_jobstatus  \
0  C2H Corp-To-Corp, C2H Independent, C2H W2, 3 M...   
1                                          Full Time   
2                                          Full Time   
3                                          Full Time   
4                                          Full Time   

                                      jobdescription               jobid  \
0  Looking for Selenium engineers...must have sol...  Dice Id : 10110693   
1  The University of Chicago has a rapidly growin...  Dice Id : 10114469   
2  GalaxE.SolutionsEvery day, our solutions affec...  Dice Id : CXGALXYS   
3  Java DeveloperFull-time/direct-hireBolingbrook...  Dice Id : 10113627   
4  Midtown based high tech firm has an immediate ...  Dice Id : matrixga   

  joblocation_address                                           jobtitle  \
0         Atlanta, GA                           AUTOMATION TEST ENGINEER   
1         Chicago, IL                      Information Security Engineer   
2      Schaumburg, IL                       Business Solutions Architect   
3     Bolingbrook, IL  Java Developer (mid level)- FT- GREAT culture,...   
4         Atlanta, GA                                    DevOps Engineer   

         postdate                                            shift  \
0      1 hour ago  Telecommuting not available|Travel not required   
1      1 week ago  Telecommuting not available|Travel not required   
2     2 weeks ago  Telecommuting not available|Travel not required   
3     2 weeks ago  Telecommuting not available|Travel not required   
4  48 minutes ago  Telecommuting not available|Travel not required   

                                              skills  \
0                                          SEE BELOW   
1  linux/unix, network monitoring, incident respo...   
2  Enterprise Solutions Architecture, business in...   
3                         Please see job description   
4  Configuration Management, Developer, Linux, Ma...   

                            uniq_id  
0  418ff92580b270ef4e7c14f0ddfc36b4  
1  8aec88cba08d53da65ab99cf20f6f9d9  
2  46baa1f69ac07779274bcd90b85d9a72  
3  3941b2f206ae0f900c4fba4ac0b18719  
4  45efa1f6bc65acc32bbbb953a1ed13b7

## Description of Each Column in the Dataset

In [4]:
jobs_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   advertiserurl             22000 non-null  object
 1   company                   21950 non-null  object
 2   employmenttype_jobstatus  21770 non-null  object
 3   jobdescription            22000 non-null  object
 4   jobid                     22000 non-null  object
 5   joblocation_address       21997 non-null  object
 6   jobtitle                  22000 non-null  object
 7   postdate                  22000 non-null  object
 8   shift                     21643 non-null  object
 9   skills                    21957 non-null  object
 10  uniq_id                   22000 non-null  object
dtypes: object(11)
memory usage: 1.8+ MB


## Cleaning the Dataset

In [5]:
jobs_cleaned_data = jobs_data.drop(columns=['postdate','shift','uniq_id','joblocation_address','employmenttype_jobstatus'])
jobs_cleaned_data.head()

advertiserurl  \
0  https://www.dice.com/jobs/detail/AUTOMATION-TE...   
1  https://www.dice.com/jobs/detail/Information-S...   
2  https://www.dice.com/jobs/detail/Business-Solu...   
3  https://www.dice.com/jobs/detail/Java-Develope...   
4  https://www.dice.com/jobs/detail/DevOps-Engine...   

                             company  \
0  Digital Intelligence Systems, LLC   
1  University of Chicago/IT Services   
2               Galaxy Systems, Inc.   
3                      TransTech LLC   
4                   Matrix Resources   

                                      jobdescription               jobid  \
0  Looking for Selenium engineers...must have sol...  Dice Id : 10110693   
1  The University of Chicago has a rapidly growin...  Dice Id : 10114469   
2  GalaxE.SolutionsEvery day, our solutions affec...  Dice Id : CXGALXYS   
3  Java DeveloperFull-time/direct-hireBolingbrook...  Dice Id : 10113627   
4  Midtown based high tech firm has an immediate ...  Dice Id : matrixga   

                                            jobtitle  \
0                           AUTOMATION TEST ENGINEER   
1                      Information Security Engineer   
2                       Business Solutions Architect   
3  Java Developer (mid level)- FT- GREAT culture,...   
4                                    DevOps Engineer   

                                              skills  
0                                          SEE BELOW  
1  linux/unix, network monitoring, incident respo...  
2  Enterprise Solutions Architecture, business in...  
3                         Please see job description  
4  Configuration Management, Developer, Linux, Ma...

In [6]:
jobs_cleaned_data.drop_duplicates()

advertiserurl  \
0      https://www.dice.com/jobs/detail/AUTOMATION-TE...   
1      https://www.dice.com/jobs/detail/Information-S...   
2      https://www.dice.com/jobs/detail/Business-Solu...   
3      https://www.dice.com/jobs/detail/Java-Develope...   
4      https://www.dice.com/jobs/detail/DevOps-Engine...   
...                                                  ...   
21995  https://www.dice.com/jobs/detail/Web-Designer-...   
21996  https://www.dice.com/jobs/detail/Senior-Front-...   
21997  https://www.dice.com/jobs/detail/QA-Analyst-Sa...   
21998  https://www.dice.com/jobs/detail/Tech-Lead%252...   
21999  https://www.dice.com/jobs/detail/C%2526%252347...   

                                 company  \
0      Digital Intelligence Systems, LLC   
1      University of Chicago/IT Services   
2                   Galaxy Systems, Inc.   
3                          TransTech LLC   
4                       Matrix Resources   
...                                  ...   
21995                     IAC Publishing   
21996                Omega Solutions Inc   
21997          San Francisco Health Plan   
21998                     IAC Publishing   
21999          Technology Resource Group   

                                          jobdescription               jobid  \
0      Looking for Selenium engineers...must have sol...  Dice Id : 10110693   
1      The University of Chicago has a rapidly growin...  Dice Id : 10114469   
2      GalaxE.SolutionsEvery day, our solutions affec...  Dice Id : CXGALXYS   
3      Java DeveloperFull-time/direct-hireBolingbrook...  Dice Id : 10113627   
4      Midtown based high tech firm has an immediate ...  Dice Id : matrixga   
...                                                  ...                 ...   
21995   Company Description We are searching for a ta...  Dice Id : 10112803   
21996   CONTACT - priya@omegasolutioninc.com / 408-45...  Dice Id : 10289500   
21997  Do you take pride in your work knowing that th...  Dice Id : 10115761   
21998  Company Description What We Can Offer YouAs th...  Dice Id : 10112803   
21999  Experience in C/C++ ProgrammingDevelopment exp...  Dice Id : 90734436   

                                                jobtitle  \
0                               AUTOMATION TEST ENGINEER   
1                          Information Security Engineer   
2                           Business Solutions Architect   
3      Java Developer (mid level)- FT- GREAT culture,...   
4                                        DevOps Engineer   
...                                                  ...   
21995                                       Web Designer   
21996  Senior Front End Web Developer - Full Time at ...   
21997                                         QA Analyst   
21998                               Tech Lead-Full Stack   
21999                                   C/C++ Programmer   

                                                  skills  
0                                              SEE BELOW  
1      linux/unix, network monitoring, incident respo...  
2      Enterprise Solutions Architecture, business in...  
3                             Please see job description  
4      Configuration Management, Developer, Linux, Ma...  
...                                                  ...  
21995  UI/UX mobile apps, interaction design, digital...  
21996  JavaScript, HTML5, CSS3, Bootstrap, AJAX, Reac...  
21997  SDLC, ALM, SQL, T-SQL, RedGate, Team Foundatio...  
21998  Python, Ruby, Go, Clojure, Java, NoSQL-Databas...  
21999                                               Null  

[22000 rows x 6 columns]

In [7]:
jobsNull = jobs_cleaned_data[jobs_cleaned_data["skills"]=="Null"].index ##getting the particular row where value of column

jobsDesc1 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="Please See job description"].index

jobsDesc2 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="(See Job Description)"].index

jobsDesc3 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="SEE BELOW"].index

jobsDesc4 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="Telecommuting not available Travel not required"].index

jobsDesc5 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="Refer to Job Description"].index

jobsDesc6 = jobs_cleaned_data[jobs_cleaned_data["skills"]=="Please see Required Skills"].index


jobs_cleaned_data.drop(jobsNull, inplace=True)
jobs_cleaned_data.drop(jobsDesc1, inplace=True)
jobs_cleaned_data.drop(jobsDesc2, inplace=True)
jobs_cleaned_data.drop(jobsDesc3, inplace=True)
jobs_cleaned_data.drop(jobsDesc4, inplace=True)
jobs_cleaned_data.drop(jobsDesc5, inplace=True)
jobs_cleaned_data.drop(jobsDesc6, inplace=True)

In [8]:
jobs_cleaned_data.shape

(21792, 6)

In [9]:
jobs_cleaned_data['jobtitle'] = jobs_cleaned_data['jobtitle'].fillna('')
jobs_cleaned_data['jobdescription'] = jobs_cleaned_data['jobdescription'].fillna('')
jobs_cleaned_data['skills'] = jobs_cleaned_data['skills'].fillna('')

In [10]:
jobs_cleaned_data.shape

(21792, 6)

In [11]:
jobs_cleaned_data['jobdescription'] = jobs_cleaned_data['jobtitle'] +  jobs_cleaned_data['skills']+ jobs_cleaned_data['jobdescription']

In [12]:
jobs_cleaned_data.shape

(21792, 6)

In [13]:
jobs_cleaned_data.head()

advertiserurl  \
1  https://www.dice.com/jobs/detail/Information-S...   
2  https://www.dice.com/jobs/detail/Business-Solu...   
3  https://www.dice.com/jobs/detail/Java-Develope...   
4  https://www.dice.com/jobs/detail/DevOps-Engine...   
5  https://www.dice.com/jobs/detail/SAP-FICO-Arch...   

                             company  \
1  University of Chicago/IT Services   
2               Galaxy Systems, Inc.   
3                      TransTech LLC   
4                   Matrix Resources   
5                  Yash Technologies   

                                      jobdescription               jobid  \
1  Information Security Engineerlinux/unix, netwo...  Dice Id : 10114469   
2  Business Solutions ArchitectEnterprise Solutio...  Dice Id : CXGALXYS   
3  Java Developer (mid level)- FT- GREAT culture,...  Dice Id : 10113627   
4  DevOps EngineerConfiguration Management, Devel...  Dice Id : matrixga   
5  SAP FICO ArchitectFICO, AR, AP, Asset Manageme...  Dice Id : 10111847   

                                            jobtitle  \
1                      Information Security Engineer   
2                       Business Solutions Architect   
3  Java Developer (mid level)- FT- GREAT culture,...   
4                                    DevOps Engineer   
5                                 SAP FICO Architect   

                                              skills  
1  linux/unix, network monitoring, incident respo...  
2  Enterprise Solutions Architecture, business in...  
3                         Please see job description  
4  Configuration Management, Developer, Linux, Ma...  
5               FICO, AR, AP, Asset Management, HAHA

## Final Dataset

In [14]:
 new_df = jobs_cleaned_data[['advertiserurl','company','jobdescription','skills','jobtitle']]

In [15]:
new_df['jobdescription'] = new_df['jobdescription'].apply(lambda x:x.lower())

C:\Users\arka2\AppData\Local\Temp/ipykernel_14356/3508031578.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['jobdescription'] = new_df['jobdescription'].apply(lambda x:x.lower())


In [16]:
new_df.head(1)

advertiserurl  \
1  https://www.dice.com/jobs/detail/Information-S...   

                             company  \
1  University of Chicago/IT Services   

                                      jobdescription  \
1  information security engineerlinux/unix, netwo...   

                                              skills  \
1  linux/unix, network monitoring, incident respo...   

                        jobtitle  
1  Information Security Engineer

In [16]:
new_df['jobdescription'][1]

"information security engineerlinux/unix, network monitoring, incident response, systems administration, security accessmentthe university of chicago has a rapidly growing security program with many opportunities for a motivated person to work in a variety of roles and many technical areas. \xa0this position is responsible for providing incident response, information security assessment, monitoring, and system administration under the general direction of the information security officer and the lead information security engineer.\xa0essential functions:\xa0execute it security network monitoring and incident response procedures.\xa0lead or participate in it security projects.\xa0administer it security systems, including updates, backups, and upgrades\xa0consult, advise, and provide security assessment services to application development or acquisition projects to assess security requirements and controls and to ensure that security controls are implemented as planned.\xa0research secur

## Converting the string in the 'jobdescription' column to list

In [17]:
new_df['jobdescription'].apply(lambda x:"".join(x))

1        information security engineerlinux/unix, netwo...
2        business solutions architectenterprise solutio...
3        java developer (mid level)- ft- great culture,...
4        devops engineerconfiguration management, devel...
5        sap fico architectfico, ar, ap, asset manageme...
                               ...                        
21994    empower administratorempower3, limps•     hand...
21995    web designerui/ux mobile apps, interaction des...
21996    senior front end web developer - full time at ...
21997    qa analystsdlc, alm, sql, t-sql, redgate, team...
21998    tech lead-full stackpython, ruby, go, clojure,...
Name: jobdescription, Length: 21792, dtype: object

In [18]:
new_df['jobdescription'] = new_df['jobdescription'].apply(lambda x:"".join(x))

C:\Users\arka2\AppData\Local\Temp/ipykernel_14356/41602319.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['jobdescription'] = new_df['jobdescription'].apply(lambda x:"".join(x))


In [19]:
new_df['jobdescription'][4]

'devops engineerconfiguration management, developer, linux, management, process engineering, vmwaremidtown based high tech firm has an immediate need\xa0for an innovative devops engineer\xa0to help define dev / ops related processes,\xa0build out the automation. \xa0in this position, the dev / ops engineer\xa0will need to\xa0engineer technical solutions as well as perform process engineering. the ideal candidate has strong scripting skills for automation as well experience with configuration management, server deployment, and continuous integration and experience with tools such as\xa0chef, puppet, etc. \xa0must have experience with virtualization using vmware and linux experience is\xa0preferred.\xa0\xa0experience with\xa0go, docker, ansible, microservices, and the cloud are highly desired.\xa0\xa0 this is a permanent position with an innovative technology firm in midtown that offers excellent benefits including bleeding edge technology, very generous pto, matching 401(k), high-tech o

In [19]:
new_df['jobdescription'][5]

'sap fico architectfico, ar, ap, asset management, hahawe are looking for a senior sap fico architect to join us fulltime and support our ongoing projects and customers. must have excellent pre-sales experience.consultant should be ready for 100% travel.\xa0if interested, please send us your updated resume, best time and contact numbers to girish(dot)bandaru(at)yash(dot)com to discuss more on this opportunity.\xa0thanks & regards\xa0girish bandaruyash technologies773-828-4341girish.bandaru@yash.com'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv_second = CountVectorizer(max_features=2,stop_words='english')

In [22]:
vectors_one = cv_second.fit_transform(new_df['jobdescription']).toarray()

In [23]:
vectors_one

array([[ 0,  6],
       [ 4,  5],
       [ 0,  6],
       ...,
       [ 0,  6],
       [ 7, 15],
       [ 0,  5]], dtype=int64)

In [24]:
vectors_one.shape

(21792, 2)

In [25]:
cv = CountVectorizer(max_features=5000,stop_words='english')

## Displaying Sparse Matrix

In [26]:
cv.fit_transform(new_df['jobdescription']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
cv.fit_transform(new_df['jobdescription']).toarray().shape

(21792, 5000)

In [28]:
vectors = cv.fit_transform(new_df['jobdescription']).toarray()

## Displaying the First Job Description Vector

In [29]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

## Now display what are the top 5000 common words that occured most number of times

In [30]:
cv.get_feature_names()

C:\Users\arka2\anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '01',
 '06',
 '10',
 '100',
 '1000',
 '100k',
 '1099',
 '10g',
 '11',
 '110',
 '11g',
 '12',
 '120',
 '12c',
 '13',
 '130',
 '14',
 '140',
 '15',
 '150',
 '150k',
 '16',
 '17',
 '18',
 '180',
 '19',
 '1995',
 '1997',
 '1998',
 '1999',
 '1st',
 '20',
 '200',
 '2000',
 '2002',
 '2003',
 '2005',
 '2007',
 '2008',
 '2008r2',
 '201',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '202',
 '21',
 '212',
 '214',
 '22',
 '221',
 '23',
 '239',
 '24',
 '248',
 '24x7',
 '24x7x365',
 '25',
 '250',
 '27',
 '27001',
 '28',
 '2nd',
 '30',
 '300',
 '305',
 '307',
 '31',
 '340',
 '35',
 '360',
 '365',
 '3d',
 '3i',
 '3rd',
 '40',
 '400',
 '401',
 '401k',
 '404',
 '408',
 '415',
 '425',
 '4900',
 '4g',
 '50',
 '500',
 '5000',
 '508',
 '510',
 '53',
 '55',
 '550',
 '60',
 '600',
 '609',
 '630',
 '646',
 '65',
 '678',
 '6965',
 '70',
 '703',
 '732',
 '739',
 '75',
 '770',
 '80',
 '800',
 '802',
 '843',
 '8700',
 '888',
 '90',
 '9001',
 '908',
 '925',
 '95',
 '972',

In [31]:
len(cv.get_feature_names())

5000

In [32]:
cv = CountVectorizer(max_features=5000,stop_words='english') #approval and approvals always have to be same, they should not be different features

In [35]:
!pip install nltk

In [33]:
import nltk

## Stemming Process is Done

In [34]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [35]:
ps.stem('loved')

'love'

In [36]:
ps.stem('Information')

'inform'

In [37]:
ps.stem('Business')

'busi'

In [38]:
def stem(text):
    y = []
    
    for i in text.split(): #convert each string in text to list
        y.append(ps.stem(i))
        
    return " ".join(y)

In [39]:
new_df['jobdescription'].apply(stem)

1        inform secur engineerlinux/unix, network monit...
2        busi solut architectenterpris solut architectu...
3        java develop (mid level)- ft- great culture, m...
4        devop engineerconfigur management, developer, ...
5        sap fico architectfico, ar, ap, asset manageme...
                               ...                        
21994    empow administratorempower3, limps• hand on ex...
21995    web designerui/ux mobil apps, interact design,...
21996    senior front end web develop - full time at vi...
21997    qa analystsdlc, alm, sql, t-sql, redgate, team...
21998    tech lead-ful stackpython, ruby, go, clojure, ...
Name: jobdescription, Length: 21792, dtype: object

In [40]:
new_df['jobdescription']=new_df['jobdescription'].apply(stem)

C:\Users\arka2\AppData\Local\Temp/ipykernel_14356/957083507.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['jobdescription']=new_df['jobdescription'].apply(stem)


In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [44]:
vectors = cv.fit_transform(new_df['jobdescription']).toarray()

In [41]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
vectors.shape

(21792, 5000)

## After Stemming Most Common Words are present

In [47]:
cv.get_feature_names()

['00',
 '000',
 '01',
 '06',
 '10',
 '100',
 '1000',
 '100k',
 '1099',
 '10g',
 '11',
 '110',
 '11g',
 '12',
 '120',
 '12c',
 '13',
 '130',
 '14',
 '140',
 '15',
 '150',
 '150k',
 '16',
 '17',
 '18',
 '180',
 '19',
 '1995',
 '1996teamsoft',
 '1997',
 '1998',
 '1999',
 '1b',
 '1st',
 '20',
 '200',
 '2000',
 '2002',
 '2003',
 '2005',
 '2007',
 '2008',
 '2008r2',
 '2009',
 '201',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '202',
 '203',
 '21',
 '212',
 '214',
 '22',
 '221',
 '23',
 '233',
 '239',
 '24',
 '248',
 '24x7',
 '24x7x365',
 '25',
 '250',
 '27',
 '27001',
 '28',
 '2nd',
 '30',
 '300',
 '305',
 '307',
 '31',
 '32',
 '340',
 '35',
 '36',
 '360',
 '365',
 '3d',
 '3i',
 '3ipeople',
 '3rd',
 '40',
 '400',
 '401',
 '401k',
 '404',
 '408',
 '415',
 '425',
 '45',
 '46',
 '479',
 '4900',
 '4g',
 '50',
 '500',
 '5000',
 '501',
 '508',
 '510',
 '53',
 '549',
 '55',
 '550',
 '5993',
 '60',
 '600',
 '609',
 '630',
 '646',
 '65',
 '6500',
 '678',
 '6965',
 '70',
 

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

## Cosine-similarity is used to compare jobdescription vector with one another jobdescription vector

In [49]:
cosine_similarity(vectors)

array([[1.        , 0.12747516, 0.17130344, ..., 0.14351711, 0.17875565,
        0.11239714],
       [0.12747516, 1.        , 0.25063796, ..., 0.2019399 , 0.35139138,
        0.22230152],
       [0.17130344, 0.25063796, 1.        , ..., 0.30402729, 0.38279167,
        0.26532162],
       ...,
       [0.14351711, 0.2019399 , 0.30402729, ..., 1.        , 0.28724723,
        0.28984434],
       [0.17875565, 0.35139138, 0.38279167, ..., 0.28724723, 1.        ,
        0.32234361],
       [0.11239714, 0.22230152, 0.26532162, ..., 0.28984434, 0.32234361,
        1.        ]])

In [50]:
similarity = cosine_similarity(vectors)

In [51]:
similarity.shape

(21792, 21792)

In [52]:
similarity[0]

array([1.        , 0.12747516, 0.17130344, ..., 0.14351711, 0.17875565,
       0.11239714])

In [53]:
indices = pd.Series(new_df.index, index=new_df['skills']).drop_duplicates()

In [54]:
indices.head(20)

skills
linux/unix, network monitoring, incident response, systems administration, security accessment              1
Enterprise Solutions Architecture, business inteligence, reports, reporting                                 2
Please see job description                                                                                  3
Configuration Management, Developer, Linux, Management, Process Engineering, VMware                         4
FICO, AR, AP, Asset Management, HAHA                                                                        5
Cisco, DNS, HTTP, Networking, Network Engineer, Security, Video, VPN, Wireless                              6
.NET , C#, MVC, RESTful web services, HTTP, AWS, Azure, OOP                                                 7
C++, Developer, Development, JavaScript, User Interface                                                     8
Openstack                                                                                                  10
Uni

## Recommendation Function

In [60]:
def give_rec(skill_set, similarity = similarity):
  #Get the index corresponding to original title
  idx = indices[skill_set]

  #Get pairwise Similarity Scores
  sim_scores = list(enumerate(similarity[idx]))

  #Sort the Scores in Descending Order
  sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)

  #Scores of the 10 most similar Skills
  sim_scores = sim_scores[1:11]

  #Job Title indices
  skills_indices = [i[0] for i in sim_scores]
  #df1 = pd.DataFrame(data = jobs_cleaned_data[skills_indices], columns=['Title','Link','Name'])
  data1 = jobs_cleaned_data['jobtitle'].iloc[skills_indices]
  data2 = jobs_cleaned_data['company'].iloc[skills_indices]
  data3 = jobs_cleaned_data['advertiserurl'].iloc[skills_indices]

  #Top 10 most similar Jobs
  return data1,data2,data3

## Giving Top 10 Recommendations for a Particular Skillset

In [61]:
give_rec('linux/unix, network monitoring, incident response, systems administration, security accessment')

(12848          Enterprise Data Warehouse Architect
 18802                               Data Architect
 810                       Cognos BI Engineer (ETL)
 14842    Sr Manager, Data Architecture (macys.com)
 2874                      Data Warehouse Developer
 13462                           Sr. Data Architect
 13860                           Sr. Data Architect
 10322                     Data Warehouse Developer
 16038                           Big Data Architect
 15278                 Big Data Solutions Architect
 Name: jobtitle, dtype: object,
 12848                       Nexient- HQ
 18802    Ameex Technologies Corporation
 810              Overture Partners, LLC
 14842                            Macy's
 2874                    Custom Staffing
 13462                     Arete Systems
 13860                     Arete Systems
 10322                  Benchmark IT LLC
 16038                      GSS Infotech
 15278     Genoa International Solutions
 Name: company, dtype: object,
 12848 

In [62]:
give_rec('Cisco, DNS, HTTP, Networking, Network Engineer, Security, Video, VPN, Wireless')

(3481                          Full Stack Web Developer/RNA
 3619                              Senior Software Engineer
 2366                   Software Development Manager-C#/SQL
 18215                           Senior Software Engineer V
 19576        Principal Cloud Software Engineer / Architect
 15485    Java Web Developer - Angular, React, JavaScrip...
 9995                                  Angular JS Developer
 2467                          Software Development Manager
 2167         Sr. Software Developer (eCommerce/C# ASP.NET)
 18206                     Sr. Front End Developer - Boston
 Name: jobtitle, dtype: object,
 3481                  Shain Associates
 3619               Green Key Resources
 2366     Cardinal Technology Solutions
 18215           Northstar Travel Media
 19576                          ENTEGEE
 15485                     Techsourcers
 9995                  Sofia Technology
 2467            Patel Consultants Corp
 2167            Robert Half Technology
 18206  

In [63]:
give_rec('Analysis, Analyst, Application, Business Analyst, Business Requirements, Excel, IT, PowerPoint, Project')

(2687     Senior Product Manager, Amazon Demand-Side Pla...
 5714                                       Account Manager
 12691                            Technical Program Manager
 12898                            Technical Program Manager
 4364                             Technical Program Manager
 4650             Sr. Product Manager - Technical (Level 6)
 4346     Technical Program Manager - Fleet Management S...
 4358                           Sr. Product Manager, Comics
 21680    Senior Cloud Technical Account Manager / Hands...
 15829    Director of Product Management, Managing Expenses
 Name: jobtitle, dtype: object,
 2687                     Amazon
 5714                InfoChip LP
 12691                    Amazon
 12898                    Amazon
 4364                     Amazon
 4650                     Amazon
 4346                     Amazon
 4358                     Amazon
 21680                    Amazon
 15829    Entertainment Partners
 Name: company, dtype: object,
 2687  

In [64]:
give_rec('C++, Developer, Development, JavaScript, User Interface')

(16346            DevOps Contractor (W2 only) 12546
 13342    Software Development Engineer III - 10764
 13418    Software Development Engineer III - 10764
 21433    Software Development Engineer III - 10764
 20839           C++ Developer with Storage - 12093
 21746                              Cloud Architect
 19594                                PHP Developer
 20598              VMware Client Developer - 12325
 318                           Java Developer 12676
 21206                    Sr. C++ Developer - 12198
 Name: jobtitle, dtype: object,
 16346    Maxonic, Inc.
 13342    Maxonic, Inc.
 13418    Maxonic, Inc.
 21433    Maxonic, Inc.
 20839    Maxonic, Inc.
 21746              SCS
 19594     JMD Partners
 20598    Maxonic, Inc.
 318      Maxonic, Inc.
 21206    Maxonic, Inc.
 Name: company, dtype: object,
 16346    https://www.dice.com/jobs/detail/DevOps-Contra...
 13342    https://www.dice.com/jobs/detail/Software-Deve...
 13418    https://www.dice.com/jobs/detail/Software-Deve.

In [53]:
give_rec('.NET , C#, MVC, RESTful web services, HTTP, AWS, Azure, OOP')

(10379                         Application Support Engineer
 8746     Senior Web Application Developer- SaaS Co - Ja...
 4228                                Sr Javascript Engineer
 5334     Direct Hire Lead Software Development Engineer...
 5121       Very Senior SDE for Well-Funded Project C#/.NET
 7758                                        Java Developer
 12523         Java Applications Developer - Minnetonka, MN
 10274                            Sr. Application Developer
 9191                            Senior Front End Developer
 12446                                 Senior SOA Architect
 Name: jobtitle, dtype: object,
 10379         The McIntyre Group
 8746                 CyberCoders
 4228        Vaco - San Francisco
 5334             Maxsam Partners
 5121             Maxsam Partners
 7758       Signature Consultants
 12523         UnitedHealth Group
 10274    Burlington Coat Factory
 9191                Aureus Group
 12446    Request Technology, LLC
 Name: company, dtype: objec

In [54]:
give_rec('Consulting, Project, Sales, Sales Engineer')

(3840                                Senior Test Analyst
 19147                               Senior Test Analyst
 216                       Senior Mainframe Test Analyst
 20834    PeopleSoft Testing Manager//San Francisco, CA.
 21764                                Systems QA Analyst
 1338                             Software Test Engineer
 3703                          Quality Assurance Analyst
 19686                                    Sr. QA Analyst
 11083                       Sr. Software Testing Leader
 2639                   Team Leader-Testing & QA Analyst
 Name: jobtitle, dtype: object,
 3840      Edge Technology Services, Inc.
 19147     Edge Technology Services, Inc.
 216                           Staff Tech
 20834           Lodestar Consulting, LLC
 21764            ATR International, Inc.
 1338                         Stowe Group
 3703              Software Methods, Inc.
 19686                      integrITalent
 11083    Benjamin Douglas Consulting LLC
 2639              S

In [55]:
give_rec('Agile, CASE, Consulting, Defect Management, Manager, Management, Project, Project Management')

(6887     Systems Security Administrator - Sr/ Sr. Infor...
 14259            Information Security Engineer (SCADA/ICS)
 21353                         Director of Network Security
 17123                             Senior Security Engineer
 7008                       IT Security Engineer / Analysts
 16554                   Security Engineer (Greater Boston)
 20011                                IT Security Architect
 6884                              Cyber Security Architect
 3310                        Senior Cyber Security Engineer
 10759                       Information Security Architect
 Name: jobtitle, dtype: object,
 6887                         Finezi
 14259              Vaco - San Diego
 21353            Amarx Search, Inc.
 17123        Crescent Solutions Inc
 7008              Prestige Staffing
 16554          Blue Line Talent LLC
 20011                 Vizient, Inc.
 6884                     Travelport
 3310                  Addison Group
 10759    Red Oak Technologies, Inc